palette = "default"

[palettes.default]
aws_fg = "yellow"
aws_bg = "none"
azure_fg = "blue"
azure_bg = "none"
buf_fg = "blue"
buf_bg = "none"
bun_fg = "red"
bun_bg = "none"
c_fg = "149"
c_bg = "none"
character_success_fg = "green"
character_success_bg = "none"
character_error_fg = "red"
character_error_bg = "none"
character_vimcmd_fg = "green"
character_vimcmd_bg = "none"
character_vimcmd_visual_fg = "yellow"
character_vimcmd_visual_bg = "none"
character_vimcmd_replace_fg = "purple"
character_vimcmd_replace_bg = "none"
character_vimcmd_replace_one_fg = "purple"
character_vimcmd_replace_one_bg = "none"
claude_model_fg = "blue"
claude_model_bg = "none"
cmake_fg = "blue"
cmake_bg = "none"
cmd_duration_fg = "yellow"
cmd_duration_bg = "none"
cobol_fg = "blue"
cobol_bg = "none"
conda_fg = "green"
conda_bg = "none"
container_fg = "red"
container_bg = "none"
cpp_fg = "149"
cpp_bg = "none"
crystal_fg = "red"
crystal_bg = "none"
daml_fg = "cyan"
daml_bg = "none"
dart_fg = "blue"
dart_bg = "none"
deno_fg = "green"
deno_bg = "none"
directory_fg = "cyan"
directory_bg = "none"
directory_read_only_style_fg = "red"
directory_read_only_style_bg = "none"
direnv_fg = "bright-yellow"
direnv_bg = "none"
docker_context_fg = "blue"
docker_context_bg = "none"
dotnet_fg = "blue"
dotnet_bg = "none"
elixir_fg = "purple"
elixir_bg = "none"
elm_fg = "cyan"
elm_bg = "none"
env_var_fg = "black"
env_var_bg = "none"
erlang_fg = "red"
erlang_bg = "none"
fennel_fg = "green"
fennel_bg = "none"
fill_fg = "black"
fill_bg = "none"
fortran_fg = "purple"
fortran_bg = "none"
fossil_branch_fg = "purple"
fossil_branch_bg = "none"
fossil_metrics_added_style_fg = "green"
fossil_metrics_added_style_bg = "none"
fossil_metrics_deleted_style_fg = "red"
fossil_metrics_deleted_style_bg = "none"
gcloud_fg = "blue"
gcloud_bg = "none"
git_branch_fg = "purple"
git_branch_bg = "none"
git_commit_fg = "green"
git_commit_bg = "none"
git_metrics_added_style_fg = "green"
git_metrics_added_style_bg = "none"
git_metrics_deleted_style_fg = "red"
git_metrics_deleted_style_bg = "none"
git_state_fg = "yellow"
git_state_bg = "none"
git_status_fg = "red"
git_status_bg = "none"
gleam_fg = "#FFAFF3"
gleam_bg = "none"
golang_fg = "cyan"
golang_bg = "none"
golang_not_capable_fg = "red"
golang_not_capable_bg = "none"
gradle_fg = "bright-cyan"
gradle_bg = "none"
guix_shell_fg = "yellow"
guix_shell_bg = "none"
haskell_fg = "purple"
haskell_bg = "none"
haxe_fg = "202"
haxe_bg = "none"
helm_fg = "white"
helm_bg = "none"
hg_branch_fg = "purple"
hg_branch_bg = "none"
hg_state_fg = "yellow"
hg_state_bg = "none"
hostname_fg = "green"
hostname_bg = "none"
java_fg = "red"
java_bg = "none"
jobs_fg = "blue"
jobs_bg = "none"
julia_fg = "purple"
julia_bg = "none"
kotlin_fg = "blue"
kotlin_bg = "none"
kubernetes_fg = "cyan"
kubernetes_bg = "none"
localip_fg = "yellow"
localip_bg = "none"
lua_fg = "blue"
lua_bg = "none"
maven_fg = "bright-cyan"
maven_bg = "none"
memory_usage_fg = "white"
memory_usage_bg = "none"
meson_fg = "blue"
meson_bg = "none"
mise_fg = "purple"
mise_bg = "none"
mojo_fg = "208"
mojo_bg = "none"
nats_fg = "purple"
nats_bg = "none"
netns_fg = "blue"
netns_bg = "none"
nim_fg = "yellow"
nim_bg = "none"
nix_shell_fg = "blue"
nix_shell_bg = "none"
nodejs_fg = "green"
nodejs_bg = "none"
nodejs_not_capable_fg = "red"
nodejs_not_capable_bg = "none"
ocaml_fg = "yellow"
ocaml_bg = "none"
odin_fg = "bright-blue"
odin_bg = "none"
opa_fg = "blue"
opa_bg = "none"
openstack_fg = "yellow"
openstack_bg = "none"
os_fg = "white"
os_bg = "none"
package_fg = "208"
package_bg = "none"
perl_fg = "149"
perl_bg = "none"
php_fg = "147"
php_bg = "none"
pijul_channel_fg = "purple"
pijul_channel_bg = "none"
pixi_fg = "yellow"
pixi_bg = "none"
pulumi_fg = "5"
pulumi_bg = "none"
purescript_fg = "white"
purescript_bg = "none"
python_fg = "yellow"
python_bg = "none"
quarto_fg = "#75AADB"
quarto_bg = "none"
raku_fg = "149"
raku_bg = "none"
red_fg = "red"
red_bg = "none"
rlang_fg = "blue"
rlang_bg = "none"
ruby_fg = "red"
ruby_bg = "none"
rust_fg = "red"
rust_bg = "none"
scala_fg = "red"
scala_bg = "none"
shell_fg = "white"
shell_bg = "none"
shlvl_fg = "yellow"
shlvl_bg = "none"
singularity_fg = "blue"
singularity_bg = "none"
solidity_fg = "blue"
solidity_bg = "none"
spack_fg = "blue"
spack_bg = "none"
status_fg = "red"
status_bg = "none"
sudo_fg = "blue"
sudo_bg = "none"
swift_fg = "202"
swift_bg = "none"
terraform_fg = "105"
terraform_bg = "none"
time_fg = "yellow"
time_bg = "none"
typst_fg = "#0093A7"
typst_bg = "none"
username_style_root_fg = "red"
username_style_root_bg = "none"
username_style_user_fg = "yellow"
username_style_user_bg = "none"
vagrant_fg = "cyan"
vagrant_bg = "none"
vcsh_fg = "yellow"
vcsh_bg = "none"
vlang_fg = "blue"
vlang_bg = "none"
xmake_fg = "green"
xmake_bg = "none"
zig_fg = "yellow"
zig_bg = "none"
